Traceback (most recent call last):
  File "/home/grupos/geocean/cagigall/.conda/envs/cc_indicators/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/grupos/geocean/cagigall/.conda/envs/cc_indicators/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grupos/geocean/cagigall/.conda/envs/cc_indicators/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/grupos/geocean/cagigall/.conda/envs/cc_indicators/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/grupos/geocean/cagigall/.conda/envs/cc_indicators/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/grupos/geocean/cagigall/.conda/envs/cc_indicators/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/grupos/geocean/cagigall/.conda/envs/cc_indicators/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
data_point = xr.open_dataset(path_data).sel(lon = lon_site, lat = lat_site, method = 'nearest').load()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m data_point [38;5;241m=[39m [43mxr[49m[38;5;241;43m.[39;49m[43mopen_dataset[49m[43m([49m[43mpath_data[49m[43m)[49m[38;5;241m.[39msel(lon [38;5;241m=[39m lon_site, lat [38;5;241m=[39m lat_site, method [38;5;241m=[39m [38;5;124m'[39m[38;5;124mnearest[39m[38;5;124m'[39m)[38;5;241m.[39mload()

File [0;32m~/.conda/envs/cc_indicators/lib/python3.12/site-packages/xarray/backends/api.py:652[0m, in [0;36mopen_dataset[0;34m(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, inline_array, chunked_array_type, from_array_kwargs, backend_kwargs, **kwargs)[0m
[1;32m    649[0m     kwargs[38;5;241m.[39mupdate(backend_kwargs)
[1;32m    651[0m [38;5;28;01mif[39;00m engine [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 652[0m     engine [38;5;241m=[39m [43mplugins[49m[38;5;241;43m.[39;49m[43mguess_engine[49m[43m([49m[43mfilename_or_obj[49m[43m)[49m
[1;32m    654[0m [38;5;28;01mif[39;00m from_array_kwargs [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    655[0m     from_array_kwargs [38;5;241m=[39m {}

File [0;32m~/.conda/envs/cc_indicators/lib/python3.12/site-packages/xarray/backends/plugins.py:194[0m, in [0;36mguess_engine[0;34m(store_spec)[0m
[1;32m    186[0m [38;5;28;01melse[39;00m:
[1;32m    187[0m     error_msg [38;5;241m=[39m (
[1;32m    188[0m         [38;5;124m"[39m[38;5;124mfound the following matches with the input file in xarray[39m[38;5;124m'[39m[38;5;124ms IO [39m[38;5;124m"[39m
[1;32m    189[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mbackends: [39m[38;5;132;01m{[39;00mcompatible_engines[38;5;132;01m}[39;00m[38;5;124m. But their dependencies may not be installed, see:[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m    190[0m         [38;5;124m"[39m[38;5;124mhttps://docs.xarray.dev/en/stable/user-guide/io.html [39m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m    191[0m         [38;5;124m"[39m[38;5;124mhttps://docs.xarray.dev/en/stable/getting-started-guide/installing.html[39m[38;5;124m"[39m
[1;32m    192[0m     )
[0;32m--> 194[0m [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(error_msg)

[0;31mValueError[0m: found the following matches with the input file in xarray's IO backends: ['netcdf4', 'h5netcdf']. But their dependencies may not be installed, see:
https://docs.xarray.dev/en/stable/user-guide/io.html 
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html

